layout_spectrum: 0.2903226
color:
  saturation: 0.3530466
  brandStrength: 0.243947
  lightness: 0.7903226
  rhythmicContrast: 0.3568746
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.9032258
name: Dr Benji Acupuncture
